#!/usr/bin/env bash

# Note: replace with the directory that contains alto_to_djvu.xml
SHARE_DIR='@SHARE_DIR@'

usage() {
   echo "Usage: $0 [-d dpi] [-f fg_image_colors] pdf_input djvu_output"
   echo "-d: takes a value in the range 20-1200. The default is 600."
   echo "-f: takes a value in the range 1-4000. The default is 256."
   exit -1
}

# Options
DPI=600
FGIMGCOLORS=256
while getopts "d: f:" o
do
    case "${o}" in
        d)
            DPI=${OPTARG}
            ;;
        f)
           FGIMGCOLORS=${OPTARG}
           ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [[ "$#" -ne 2 ]]
then
   usage
fi

# Temporary directory
REALINPATH="$(realpath "$1")"
REALOUTPATH="$(realpath "$2")"
TMPDIR="$(mktemp -d)"
cd "$TMPDIR"

cleanup() {
   cd ..
   rm -r "$TMPDIR"
   exit $1
}

# Convert to DjVu
ln -s "$REALINPATH" in.pdf || cleanup -1
djvudigital --dpi=$DPI --fg-image-colors=$FGIMGCOLORS in.pdf out.djvu  || cleanup -1
rm in.pdf || cleanup -1

# Extract text from PDF
pdfalto -noImage -annotation "$REALINPATH" in.xml || cleanup -1
xsltproc --stringparam annotfile "$PWD"/in_annot.xml "$SHARE_DIR"/alto_to_djvu.xml in.xml > out.xml || cleanup -1

# Add text to DjVu
djvuxmlparser -o out.djvu out.xml || cleanup -1

# Clean up
mv out.djvu "$REALOUTPATH"
cleanup 0
